title: KPNS
description: APCSA Tri 1 Group
owner_name: KPNS Team
github_username: Krishiv111
github_repo: "KPNS-Team"
baseurl: "/KPNSTeam"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/Krishiv111"}
    - { platform: github, user_url: "https://github.com/paravsalaniwal"}
    - { platform: github, user_url: "https://github.com/nikhilc3"}
    - { platform: github, user_url: "https://github.com/STG-7"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
